# Menggunakan Python slim yang stabil
FROM python:3.9-slim

# Instal dependency sistem untuk PaddleOCR dan OpenCV
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Instal FastAPI untuk membuat endpoint API dan PaddleOCR
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy seluruh file script
COPY . .

# Jalankan server API menggunakan Uvicorn
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]